<?php
// fichier de langues en anglais

//header
define("_FAQH","FAQ");
define("_ACCUEIL","Home");
define("_MON_PROFIL","My profile");
define("_DECONNEXION","Log out");
define("_CONNEXION","Log in");

//mon profil
define("_NOM_PRENOM","Full name");
define("_ADRESSE_EMAIL","Email adress");
define("_NUMERO","Phone number");
define("_MODIFIER","Modify");
define("_PROFIL","My profile");

//footer
define("_NOUS_CONTACTER","Contact us");
define("_CGU","Terms");
define("_MENTIONS_LEGALES","Legal notice");

//accueil admin
define("_ALERTE","Alert");
define("_CAPT_TEMP","Temperature alert");
define("_CAPT_CARD","Heartbeat alert");
define("_CAPT_SON","Sound alert");
define("_GESTION","Management of access rights");
define("_CS_CANDIDAT","Create/Delete a candidate account");
define("_CS_GESTION","Create/Delete a manager account");
define("_MODIFIER_MDP","Modify a password");
define("_GERER_CAPTEUR","Manage sensors");
define("_MOD_CAPT","Change sensor thresholds");
define("_AJ_CAPT","Add a sensor");
define("_ENL_CAPT","Remove a sensor");
define("_DONNEES_CANDIDATS","Candidate data");
define("_GERER_ACTI","Manage actuators");
define("_MOD_ACTI","Modify actuator thresholds");
define("_AJ_ACTI","Add a actuator");
define("_ENL_ACTI","Remove a actuator");
define("_FAQ","Manage the FAQ page");

//deconnexion
define("_LOGOUT","Log out");
define("_QUITTE","You have been correctly disconnected");

//authentification
define("_PAGE_AUTHENTIFICATION","Authentication page");
define("_IDENTIF","Identification");
define("_NOM_UTILISA","Login :");
define("_MDP","Password :");
define("_MDP_OUBLIE","Forgotten password?");
define("_SOUVENIR","Remember my password");

//cgu
define("_PAGE_CGU","Terms");

//mentions legales
define("_PAGE_MENTION","Legal Mention");

//nous contacter
define("_PAGE_CONTACT","Contact us");

//alerte temperature
//alerte sonore
//alerte cardiaque
define("_PAGE_ALERT_TEMP","Temperature alert");
define("_PAGE_ALERT_SON","Sound alert");
define("_PAGE_ALERT_CARD","Heartbeat alert");
define("_CAPTEUR","Sensor n°");
define("_GRAPH1","Graph 1");
define("_GRAPH2","Graph 2");
define("_DONNEES_CAPT","Sensor data");
define("_MIN","Minimum : ");
define("_MAX","Maximum : ");
define("_MOY","Average : ");
define("_INTERVALLE","Adapted interval : ");

//gestion acces candidat et gestionnaire
define("_CREER_CANDIDAT","Créer un compte candidat");
define("_CREER_GESTIONNAIRE","Créer un compte gestionnaire");
define("_SUP_CANDIDAT","Supprimer un compte candidat");
define("_SUP_GESTIONNAIRE","Supprimer un compte gestionnaire");
define("_SAISIR_MDP","Saisir votre mot de passe pour valider");
define("_SAISIR_CANDIDAT","Saisir l'adresse mail du candidat");
define("_SAISIR_GESTIONNAIRE","Saisir l'adresse mail du gestionnaire");

define("_SAISIR_CAND","Saisir le nom d'utilisateur du nouveau candidat");
define("_SAISIR_GEST","Saisir le nom d'utilisateur du nouveau gestionnaire");
?>
